# Generated by Django 4.0.4 on 2022-05-13 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.emailaccount'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.settlement', verbose_name='To settlement'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='vfs_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.vfsaccount'),
        ),
    ]
