# Generated by Django 4.0.4 on 2022-05-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='phone_code',
            field=models.CharField(default=123, max_length=4, verbose_name='Phone code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='contact_number',
            field=models.CharField(max_length=14, verbose_name='Phone number'),
        ),
    ]
