# Generated by Django 4.0.4 on 2022-07-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='visa_centre',
            field=models.CharField(choices=[('0', 'None'), ('Poland Visa Application Center - Ankara', 'Ankara'), ('Poland Visa Application Center-Antalya', 'Antalya'), ('Poland Visa Application Center-Istanbul (Beyoglu)', 'Istanbul (Beyoglu)'), ('Poland Visa Application Center-Gaziantep', 'Gaziantep'), ('Poland Visa Application Center-Izmir', 'Izmir'), ('Poland Visa Application Center-Trabzon', 'Trabzon')], default='0', max_length=255),
        ),
    ]
