# Generated by Django 4.0.4 on 2022-05-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_applicant_phone_code_alter_applicant_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.CharField(max_length=255, verbose_name='Applicant id number')),
                ('card_id', models.CharField(max_length=255, verbose_name='Card id number')),
                ('sms_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sms id number')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Is processed')),
            ],
        ),
    ]
