# Generated by Django 4.0.4 on 2022-07-12 10:48

from re import M
from django.db import migrations


class Migration(migrations.Migration):

    def migrate_beyoglu_to_istanbul_beyoglu(apps, schema_editor):
        Applicant = apps.get_model('webapp', 'Applicant')
        beyoglu_applicants = Applicant.objects.filter(visa_centre='Poland Visa Application Center-Beyoglu')
        Applicant.objects.bulk_update(
            [
                Applicant(id=app.id, visa_centre='Poland Visa Application Center-Istanbul (Beyoglu)')
                for app in beyoglu_applicants
            ],
            ['visa_centre'],
            batch_size=1000
        )

    dependencies = [
        ('webapp', '0002_alter_applicant_visa_centre'),
    ]

    operations = [
        migrations.RunPython(migrate_beyoglu_to_istanbul_beyoglu)
    ]
