# Generated by Django 4.0.4 on 2022-05-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='sms_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sms code'),
        ),
    ]
