# Generated by Django 4.0.4 on 2022-05-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_queue_sms_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='subcategory',
            field=models.CharField(choices=[('1- Higher Education / Yuksek Ogrenim / studia wyzsze', '1- Higher Education'), ('2- Turkish citizens - work permit / TC vatandaslari - calisma Izni / obywatele Turcji - w celu wykonywania pracy', '2- Turkish citizens'), ('3- Foreigners - work permit/ Yabanci vatandaslar - calisma Izni / cudzoziemcy - w celu wykonywania pracy', '3- Foreigners'), ('4- Long-Stay others / Diger Uzun Donem / wiza typu D w celu innym niz wymienione', '4- Long-Stay others')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='visa_center',
            field=models.CharField(choices=[('Poland Visa Application Center - Ankara', 'Ankara'), ('Poland Visa Application Center-Antalya', 'Antalya'), ('Poland Visa Application Center-Beyoglu', 'Beyoglu'), ('Poland Visa Application Center-Gaziantep', 'Gaziantep'), ('Poland Visa Application Center-Izmir', 'Izmir'), ('Poland Visa Application Center-Trabzon', 'Trabzon')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
