# Generated by Django 4.0.4 on 2022-05-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_queue_sms_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_busy',
            field=models.BooleanField(default=False, verbose_name='Is busy card'),
        ),
    ]
