# Generated by Django 4.0.4 on 2022-05-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_applicant_visa_center'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='visa_center',
            new_name='visa_centre',
        ),
    ]
