# Generated by Django 4.0.4 on 2022-05-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_applicant_visa_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='phone_number',
            field=models.CharField(default=123123123, max_length=25, verbose_name='Phone nubmer'),
            preserve_default=False,
        ),
    ]
