# Generated by Django 4.0.4 on 2022-05-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_card_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='subcategory',
            field=models.CharField(choices=[('1- Higher Education / Yuksek Ogrenim / studia wyzsze', '1- Higher Education'), ('2- Turkish citizens - work permit / TC vatandaslari - calisma Izni / obywatele Turcji - w celu wykonywania pracy', '2- Turkish citizens'), ('3- Foreigners - work permit/ Yabanci vatandaslar - calisma Izni / cudzoziemcy - w celu wykonywania pracy', '3- Foreigners'), ('4- Long-Stay others / Diger Uzun Donem / wiza typu D w celu innym niz wymienione', '4- Long-Stay others')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
